apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-backend
  template:
    metadata:
      labels:
        app: task-backend
    spec:
      containers:
        - name: task-backend
          image: kauxp/task-backend:latest
          ports:
            - containerPort: 3000
