apiVersion: v1
kind: Service
metadata:
  name: task-backend-service
spec:
  # Use NodePort for local/on-prem, LoadBalancer for cloud providers
  type: NodePort
  selector:
    app: task-backend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30007
